### ISSUE TITLE
Add Features

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/Calculator#4]
## Wants to add new features
- Calculating perfect square
- Calculating square root
- Calculating factorial of a number

**Comment by manasivaraiya** [comment]
I'd like to conribute to this

**Comment by manasivaraiya** [comment]
I'd like to contribute to this!

**Comment by manasivaraiya** [comment]
Just a small doubt! 
You want these programs in cpp right?? 
Or do you want these features on the calculator??

**Comment by Sanchitbajaj02** [comment]
I want these features in the calculator

**Comment by tausiq2003** [comment]
Can I work on this for hacktoberfest2021

**Comment by Sanchitbajaj02** [comment]
Yes you can @tausiq2003

**Comment by tausiq2003** [comment]
I am just working with the cpp file
